language: java
env:
  global:
  - GH_REF: github.com/tensorics/tensorics-core.git
  - secure: 0UbgpdALG1DKxB/UgyimwADcWliOt52iWCkahUFv2v2u9R8B/Vn8f9d4HOiKrVxuu1q38Hwimkse/+r5a2IFroJCFQk+R0D8gc61GeKFlwN+dkNJ/CSVF17LehnA0vPkFSTvfAjqkhiOZUcTxdEKz97aAaFN5Wr2n8GpXzhIK59LC2hL8uF87NbTS2UXzrIErEUfqfX/dul0AnSKD9ZmTUDEmQDEvnutMhcqLFw1ED9N8wcSEfqu05/GGQeC1SjYwK+PT6nHSGSiEulPI4odsFGObmC8GeyAn6F+lg8AiUwJ8zWzWGXKsIO8ngohWpRC0TUu164IeB9fm2zXDHH9Rg2cK1d7P3xUu5ohRY5tH7YCJg33Ixv7FD3E/oH592TarKD42dsk19f/5sZtqVCJ0/A0NzFoLdLzaZNJpWEI6wnF7B9j8mIYWcsKpWUcxzvgSw/ZvVvcQYBiroD4UGeHs+LNJsYwN3+fzfMa1LUxDik/qe/+mzJfHRl2jBA06WlCqNgDSQ62MLNvHdLQvLOblkYxDyzrZv3VNIQ65ec9MmhCd5nD6QPiTP/TWl2eXYlZACWMIkJaRAEFbX6kZsym7f180NQjSeS2fPPG2rmYXL7z6Ygg2NPAbLt/pOVjpKwKSe4g3B1o396y+TfZfDhH/RBeugu9BWDh9OAe649sQQY=
  - secure: v8X4M0kGy5EF0m3fwEkJzscWYZyW7tMEHpSkPVff7WRkiu9AR/koKWnKQZnK9CNOFNbHUVTQXCOwZ2dS31erbH6u0J6XuSyJWgGr+abvDFsHfNNrmJH3WMSSYe8qnG/x8zVuQtcZQVd0DA2+bfX+wl5zxYb3qBKwulrTL3z+cGC0N/ik/exucMeU5IpwhMa24MUhnVKzeX3Qyzy2u4k79qS9nV/spkqFNeTJ0IPxtkBWru1JcbAUobERjv9FrV/ZjKRByAAskgFBogms0UvwYCwKSWY7L/LACywfMAzAQLJSY+k6JP6V/xdR+sK5gntgp19To0bhC2jDKlEHDJR4RksvLVYg8f7vtq1Uqsrvy7mFScQuRmMSIBzRxDhj3ajK+csnprMvoEltC9GVlN+CH7IfNJTK3rD3dYshkxCKDFWGf21IrCMNhMnXyeZwSDbjA0/u6/zva/33xCP2KxWiKvR9c/X9DYyevPO/ZDkhvvaYePZOQsRjGLbjodpjWHkZxElsTstPAmTLDEPRgaW/ThOOdFqiEi0JMMhGSl0Xusg0EciT0P3l9bPUCEGIe0/XbBZwkDu5zjKHHhW9JHZn4bo9y5+38Fq3LYCBL7dCIyLkRgSsMzKmqLz69apKKI2krC33NxaWtvP4MuEXJKPVh/Yf5pCXxmNa5k9y01MW8tA=
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh ./scripts/deploy-jars.sh
  on:
    tags: true
after_success:
  provider: script
  script: /bin/sh ./scripts/deploy-gh-pages.sh
jdk:
  - oraclejdk8